edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

use_field_init_shorthand = true
use_try_shorthand = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
normalize_comments = true
wrap_comments = true
comment_width = 100

fn_params_layout = "Tall"
chain_width = 80